import { ThemeProvider } from "@/providers/theme-provider";
import "./globals.css";
import "@/public/registry/themes.css";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";

import ModalsProvider from "@/providers/modals-provider";
import Navbar from "@/components/Navbar";
import prismadb from "@/lib/prisma";
import ToasterProvider from "@/providers/toaster-provider";
import { ThemeWrapper } from "@/providers/theme-wrapper";
import { ThemeSwitcher } from "@/components/theme-switcher";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const doctors = await prismadb.doctor.findMany();
  return (
    <html lang="en">
      <ThemeWrapper defaultTheme="green" className="wax-w-screen">
        <ThemeSwitcher />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <>
            <Navbar doctors={doctors} />
            <ModalsProvider />
            <ToasterProvider />
            {children}
          </>
        </ThemeProvider>
      </ThemeWrapper>
    </html>
  );
}
